<?php

$config = array(
             	'persons' => array(array(
                                	'field'=>'relationship_id',
                                	'label'=>'Relationship_id',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'slug',
                                	'label'=>'Slug',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'first_name',
                                	'label'=>'First_name',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'last_name',
                                	'label'=>'Last_name',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'institutional_affiliation',
                                	'label'=>'Institutional_affiliation',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'departmental_affiliation',
                                	'label'=>'Departmental_affiliation',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'email',
                                	'label'=>'Email',
                                	'rules'=>'required|trim|valid_email|xss_clean'
                                ),
								array(
                                	'field'=>'website',
                                	'label'=>'Website',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'gender',
                                	'label'=>'Gender',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'ethnicity',
                                	'label'=>'Ethnicity',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'research_interests',
                                	'label'=>'Research_interests',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'image',
                                	'label'=>'Image',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'bio',
                                	'label'=>'Bio',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'pw_salt',
                                	'label'=>'Pw_salt',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'pw_hash',
                                	'label'=>'Pw_hash',
                                	'rules'=>'trim|xss_clean'
                                ))
			   );
			   
?>